openapi: 3.0.0
info:
  version: ""
  title: ""
  description: ""
servers: []
paths:
  /track/{trackId}:
    get:
      summary: Retrieve a track
      description: Returns a track corresponding to specified id
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Track'
            application/vnd.geo+json:
              schema:
                $ref: '#/components/schemas/Geojson'
          description: A Track
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Track not found
      tags:
      - track
      parameters:
      - in: header
        name: Accept
        schema:
          type: string
          enum:
          - application/json
          - application/vnd.geo+json
        required: false
        description: The type of content to be returned, json or geojson
      - in: path
        name: trackId
        schema:
          type: string
        required: true
        description: uuid of the track
  /tracks/near/{lon}/{lat}:
    get:
      summary: Retrieve tracks near a point
      description: Returns a tracks near a point within a radius of 10km, sorted by
        proximity
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Track'
            application/vnd.geo+json:
              schema:
                $ref: '#/components/schemas/Geojson'
          description: An Array of Tracks
      tags:
      - track
      parameters:
      - in: path
        name: lat
        schema:
          type: string
        required: true
        description: the latitude of the point
      - in: path
        name: lon
        schema:
          type: string
        required: true
        description: the longitude of the point
components:
  schemas:
    Address:
      type: object
      properties:
        city:
          type: string
        countryCode:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        position:
          nullable: true
          $ref: '#/components/schemas/geojson'
    Comment:
      type: object
      properties:
        content:
          type: string
        creation:
          type: string
          format: date-time
        id:
          type: string
        modification:
          type: string
          format: date-time
        user:
          $ref: '#/components/schemas/User'
    Elevation:
      type: array
      items:
        type: number
    NearTrack:
      type: object
      properties:
        Distance:
          type: number
        ID:
          type: string
    OSMAddress:
      type: object
      properties:
        city:
          type: string
        country:
          type: string
        country_code:
          type: string
        county:
          type: string
        hamlet:
          type: string
        postcode:
          type: string
        public_building:
          type: string
        road:
          type: string
        state:
          type: string
        town:
          type: string
        village:
          type: string
    OsmPlace:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/OSMAddress'
        boundingbox:
          type: array
          items:
            type: string
        display_name:
          type: string
        lat:
          type: string
        licence:
          type: string
        lon:
          type: string
        osm_id:
          type: string
        osm_type:
          type: string
        place_id:
          type: string
    Picture:
      type: object
      properties:
        caption:
          nullable: true
          type: string
        creation:
          type: string
          format: date-time
        height:
          type: integer
        id:
          type: string
        position:
          nullable: true
          $ref: '#/components/schemas/geojson'
        url:
          type: string
        width:
          type: integer
    Poi:
      type: object
      properties:
        caption:
          type: string
        creation:
          nullable: true
          type: string
          format: date-time
        icon:
          type: string
        id:
          type: string
        modification:
          nullable: true
          type: string
          format: date-time
        position:
          nullable: true
          $ref: '#/components/schemas/geojson'
    Rating:
      type: object
      additionalProperties: true
    Track:
      type: object
      properties:
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
        creation:
          type: string
          format: date-time
        description:
          type: string
        distance:
          type: integer
        downloads:
          type: integer
        elevationGain:
          type: integer
        elevationLoss:
          type: integer
        endAddress:
          nullable: true
          $ref: '#/components/schemas/Address'
        id:
          type: string
        name:
          type: string
        pictures:
          type: array
          items:
            $ref: '#/components/schemas/Picture'
        pois:
          type: array
          items:
            $ref: '#/components/schemas/Poi'
        rating:
          $ref: '#/components/schemas/Rating'
        startAddress:
          nullable: true
          $ref: '#/components/schemas/Address'
        user:
          $ref: '#/components/schemas/User'
        video:
          type: array
          items:
            $ref: '#/components/schemas/Video'
    User:
      type: object
      properties:
        creation:
          type: string
          format: date-time
        id:
          type: string
        modification:
          nullable: true
          type: string
          format: date-time
        name:
          type: string
    Video:
      type: object
      properties:
        creation:
          nullable: true
          type: string
          format: date-time
        id:
          nullable: true
          type: string
        modification:
          nullable: true
          type: string
          format: date-time
        platform:
          nullable: true
          type: string
        slug:
          nullable: true
          type: string
        trackId:
          nullable: true
          type: string
    geometry:
      type: object
      properties:
        bbox:
          type: array
          items:
            type: number
        type:
          $ref: '#/components/schemas/geojson'
